defaults: &defaults
  working_directory: ~/shard-manager
  docker:
    - image: circleci/node:8.9.4

version: 2
executorType: machine
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install NPM Dependencies
          command: npm install
      - run:
          name: Run Test Suite
          command: npm run test:pr

workflows:
  version: 2
  build_publish:
      jobs:
        - test:
            filters:
              tags:
                only: /.*/
